[package]
name = "common"
version = "0.1.0"
edition = "2021"
workspace = ".."

[dependencies]
rand = "0.8.5"
sha2 = "0.10.6"
bincode = "1.3.3"
thiserror = "1.0.40"
serde = { version = "1.0.164", features = ["derive"] }
wtransport = { git = "https://github.com/BiagioFesta/wtransport.git" }

